# Generated by Django 5.2.13 on 2026-07-25 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='From',
            new_name='Form',
        ),
        migrations.RenameField(
            model_name='form',
            old_name='data',
            new_name='date',
        ),
    ]
